.PHONY: help install dev build test test-integration test-smoke lint-arch lint verify setup-env start-server teardown-env clean

help:
	@echo "Agent Manager - Available Commands"
	@echo "======================================"
	@echo ""
	@echo "  make install           - Install root + agent-manager deps"
	@echo "  make dev               - Start Vite dev server"
	@echo "  make build             - Build for production"
	@echo "  make test              - Run Vitest unit tests"
	@echo "  make test-integration  - Run API-level integration tests (needs .env.test)"
	@echo "  make test-smoke        - Run integration smoke suite only"
	@echo "  make lint-arch         - Run architectural linters"
	@echo "  make lint              - Alias for lint-arch"
	@echo "  make verify            - Run end-to-end verification scripts"
	@echo "  make clean             - Clean build artifacts"
	@echo ""

install:
	@echo "Installing dependencies..."
	@cd agent-manager && npm install
	@cd agent-manager/server && npm install
	@echo "✓ Dependencies installed"

dev:
	@echo "Starting Vite dev server..."
	@cd agent-manager && npm run dev

build:
	@echo "Building agent-manager (frontend bundle)..."
	@cd agent-manager && npm run build
	@echo "✓ Build complete: agent-manager/dist/"

test:
	@echo "Running unit tests..."
	@cd agent-manager && npx vitest run tests/unit

test-integration:
	@echo "Running API-level integration tests against $$TEST_BASE_URL ..."
	@cd agent-manager && npm run test:integration

test-smoke:
	@echo "Running integration smoke suite ..."
	@cd agent-manager && npm run test:integration:smoke

clean:
	@echo "Cleaning build artifacts..."
	@rm -rf agent-manager/dist agent-manager/.vite
	@echo "✓ Clean complete"

# --- FIXED TARGETS (do NOT modify — generated by scaffold) ---

lint-arch:
	@echo "Checking architecture constraints..."
	@for f in scripts/lint-deps.*; do \
		case "$$f" in *.sh) bash "$$f" ;; *.py) python3 "$$f" ;; *.go) go run "$$f" ;; esac; \
	done
	@for f in scripts/lint-quality.*; do \
		case "$$f" in *.sh) bash "$$f" ;; *.py) python3 "$$f" ;; *.go) go run "$$f" ;; esac; \
	done
	@echo "✓ Architecture checks passed"

lint: lint-arch
	@echo "✓ All lint checks passed"

verify:
	@echo "Running end-to-end verification..."
	@for f in scripts/verify/*.sh; do \
		echo "→ $$f"; \
		bash "$$f" || exit 1; \
	done
	@echo "✓ All verification scenarios passed"

setup-env:
	./harness/scripts/setup-env.sh

start-server:
	./harness/scripts/start-server.sh

teardown-env:
	./harness/scripts/teardown-env.sh
