import { DEFAULT_OOS_ASSUME_ROLE } from './constants.js'

export function buildCheckpointBackupScheduleWrapperTemplateContent() {
  return [
    'FormatVersion: OOS-2019-06-01',
    'Description: Agent Manager checkpoint backup scheduled wrapper',
    'Parameters:',
    '  timerTrigger:',
    '    Type: Json',
    '  templateName:',
    '    Type: String',
    '    AssociationProperty: TemplateName',
    '  templateParameters:',
    '    Type: Json',
    '    AssociationProperty: TemplateParameter',
    '    AssociationPropertyMetadata:',
    '      TemplateName: $templateName',
    '  OOSAssumeRole:',
    '    Type: String',
    `    Default: ${DEFAULT_OOS_ASSUME_ROLE}`,
    "RamRole: '{{ OOSAssumeRole }}'",
    'Tasks:',
    '  - Name: timerTrigger',
    "    Action: 'ACS::TimerTrigger'",
    '    Properties:',
    '      Type:',
    '        Fn::Select:',
    '          - type',
    "          - '{{ timerTrigger }}'",
    '      Expression:',
    '        Fn::Select:',
    '          - expression',
    "          - '{{ timerTrigger }}'",
    '      EndDate:',
    '        Fn::Select:',
    '          - endDate',
    "          - '{{ timerTrigger }}'",
    '      TimeZone:',
    '        Fn::Select:',
    '          - timeZone',
    "          - '{{ timerTrigger }}'",
    '  - Name: executeTask',
    "    Action: 'ACS::Template'",
    '    Properties:',
    "      TemplateName: '{{ templateName }}'",
    "      Parameters: '{{ templateParameters }}'"
  ].join('\n')
}
